#ifndef DEFAULTVALUEMACROS_H
#define DEFAULTVALUEMACROS_H

#define PROPERTY_DECL_HELPER(P_TYPE, P_READ, P_WRITE)\
public:\
    P_TYPE P_READ() const;\
public slots:\
    void P_WRITE(P_TYPE value);




#define PROPERTY_DEF_HELPER(CLASS_NAME, UI_ELEMENT_NAME, UI_ELEMENT_READ, UI_ELEMENT_WRITE, P_TYPE, P_READ, P_WRITE)\
P_TYPE CLASS_NAME::P_READ() const {\
    return ui->UI_ELEMENT_NAME->UI_ELEMENT_READ();\
}\
\
void CLASS_NAME::P_WRITE(P_TYPE value) {\
    ui->UI_ELEMENT_NAME->UI_ELEMENT_WRITE(value);\
}

#define CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, UI_ELEMENT_CLASS, UI_ELEMENT_CHANGE_SIG, P_CHANGE_SIG)\
    connect(ui->UI_ELEMENT_NAME, &UI_ELEMENT_CLASS::UI_ELEMENT_CHANGE_SIG,\
            this, &CLASS_NAME::P_CHANGE_SIG);



//====================== Definitions for Specific types =========================

// UnifiedCheckbox.
#define UNIFIED_CB_DEFAULT_VALUE_DEF(CLASS_NAME, UI_ELEMENT_NAME, P_READ, P_WRITE)\
    PROPERTY_DEF_HELPER(CLASS_NAME, UI_ELEMENT_NAME, defaultValue, setDefaultValue, bool, P_READ, P_WRITE)

#define UNIFIED_CB_CONNECT(CLASS_NAME, UI_ELEMENT_NAME, P_DEFAULT_VALUE_CHANGED_SIG, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, UnifiedCheckBox, defaultValueChanged, P_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, UnifiedCheckBox, valueChanged, HAS_CHANGES_SIG)


// DefaultRestorableSpinBox
#define DR_SPIN_BOX_DEFAULT_VALUE_DEF(CLASS_NAME, UI_ELEMENT_NAME, P_READ, P_WRITE)\
    PROPERTY_DEF_HELPER(CLASS_NAME, UI_ELEMENT_NAME, defaultValue, setDefaultValue, int, P_READ, P_WRITE)

#define DR_SPIN_BOX_CONNECT(CLASS_NAME, UI_ELEMENT_NAME, P_DEFAULT_VALUE_CHANGED_SIG, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, DefaultRestorableSpinBox, defaultValueChanged, P_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, DefaultRestorableSpinBox, valueChanged, HAS_CHANGES_SIG)

#define CYCLE_DURATION_CONNECT(CLASS_NAME, UI_ELEMENT_NAME, P_DEFAULT_VALUE_CHANGED_SIG, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, CycleDurationConfigWidget, defaultValueChanged, P_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, CycleDurationConfigWidget, valueChanged, HAS_CHANGES_SIG)


// ColorSelectionWidget
#define COLOR_SELECT_DEFAULT_VALUE_DEF(CLASS_NAME, UI_ELEMENT_NAME, P_READ, P_WRITE)\
    PROPERTY_DEF_HELPER(CLASS_NAME, UI_ELEMENT_NAME, defaultValue, setDefaultValue, QColor, P_READ, P_WRITE)

#define COLOR_SELECT_CONNECT(CLASS_NAME, UI_ELEMENT_NAME, P_DEFAULT_VALUE_CHANGED_SIG, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, ColorSelectionWidget, defaultValueChanged, P_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, ColorSelectionWidget, valueChanged, HAS_CHANGES_SIG)


// InterpolationSelectorWidget
#define INTERPOLATION_DEFAULT_VALUE_DEF(CLASS_NAME, UI_ELEMENT_NAME, P_READ, P_WRITE)\
    PROPERTY_DEF_HELPER(CLASS_NAME, UI_ELEMENT_NAME, defaultValue, setDefaultValue, Interpolation::Curve, P_READ, P_WRITE)

#define INTERPOLATION_CONNECT(CLASS_NAME, UI_ELEMENT_NAME, P_DEFAULT_VALUE_CHANGED_SIG, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, InterpolationSelectorWidget, defaultValueChanged, P_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, InterpolationSelectorWidget, curveSelectionChanged, HAS_CHANGES_SIG)

// BrightnessSelectionWidget
#define BRIGHTNESS_SLIDER_DEFAULT_VALUE_DEF(CLASS_NAME, UI_ELEMENT_NAME, P_READ_MIN, P_WRITE_MIN, P_READ_MAX, P_WRITE_MAX)\
    PROPERTY_DEF_HELPER(CLASS_NAME, UI_ELEMENT_NAME, defaultMinimum, setDefaultMinimum, int, P_READ_MIN, P_WRITE_MIN)\
    PROPERTY_DEF_HELPER(CLASS_NAME, UI_ELEMENT_NAME, defaultMaximum, setDefaultMaximum, int, P_READ_MAX, P_WRITE_MAX)

#define BRIGHTNESS_SLIDER_CONNECT(CLASS_NAME, UI_ELEMENT_NAME, P_MIN_DEFAULT_VALUE_CHANGED_SIG, P_MAX_DEFAULT_VALUE_CHANGED_SIG, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, BrightnessSelectionWidget, defaultMinimumChanged, P_MIN_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, BrightnessSelectionWidget, defaultMaximumChanged, P_MAX_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, BrightnessSelectionWidget, minValueChanged, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, BrightnessSelectionWidget, maxValueChanged, HAS_CHANGES_SIG)

// UnificationDropDownWidget
#define UNIFICATION_DD_DEFAULT_VALUE_DEF(CLASS_NAME, UI_ELEMENT_NAME, P_READ, P_WRITE)\
    PROPERTY_DEF_HELPER(CLASS_NAME, UI_ELEMENT_NAME, defaultValue, setDefaultValue, UnificationKindObject::Kind, P_READ, P_WRITE)

#define UNIFICATION_DD_CONNECT(CLASS_NAME, UI_ELEMENT_NAME, P_DEFAULT_VALUE_CHANGED_SIG, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, UnificationDropDownWidget, defaultValueChanged, P_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, UnificationDropDownWidget, unificationKindChanged, HAS_CHANGES_SIG)

// DefaultRestorableCheckBox
#define DF_CB_CONNECT(CLASS_NAME, UI_ELEMENT_NAME, P_DEFAULT_VALUE_CHANGED_SIG, HAS_CHANGES_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, DefaultRestorableCheckBox, defaultValueChanged, P_DEFAULT_VALUE_CHANGED_SIG)\
    CONNECT_CHANGE_SIG_HELPER(CLASS_NAME, UI_ELEMENT_NAME, DefaultRestorableCheckBox, valueChanged, HAS_CHANGES_SIG)

#endif // DEFAULTVALUEMACROS_H
